DJ1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('myapp.urls')),
    path('',include('moto.urls')),
    path('',include('caisseTana.urls')),
    path('',include('caisseTamatave.urls')),
    path('',include('versement.urls')),
    path('',include('importateur.urls')),
    path('',include('exportateur.urls')),
    path('',include('compagnie.urls')),
    path('',include('operation.urls')),
    path('',include('facture.urls')),
    path('accounts/', include('allauth.urls')),
    path('',include('accounts.urls')),
    path('',include('commercial.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facture/urls.py
from django.urls import path
from facture import views
urlpatterns = [
    path('facture/edit/<int:id>',views.editFacture,name='editFacture'),
    path('facture/preview/<int:id>',views.previewFacture,name='previewFacture'),
    path('facture/initFacture',views.initFacture,name='initFacture'),
    path('facture/editFactureMoto/<int:id>',views.editFactureMoto,name='editFactureMoto'),
    path('facture/editBLMoto/<int:id>',views.editBLMoto,name='editBLMoto'),
    path('facture/previewFactureMoto/<int:id>',views.previewFactureMoto,name='previewFactureMoto'),
    path('facture/previewBLMoto/<int:id>',views.previewBLMoto,name='previewBLMoto'),
]

facture/models.py
from django.db import models
from operation.models import Operation
# Create your models here.
class FactureOperation(models.Model):
    idOp = models.ForeignKey(Operation,on_delete=models.CASCADE)
    OT_Honoraire = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Autres_Montant = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    BAD_Montant = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Overstay_Montant = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Surestaries_Montant = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Debarquement = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Magasinage_Montant = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Droit_Compromis = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Amende_Montant = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    OV_Montant = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    OV_Docker = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Montant_Fret = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Immobilisation = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Num_Facture = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Nom_Client = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Adresse_Client = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Contact_Client = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    email_client = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Date_Facture = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    SousTotal = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Tax = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    TotalFacture = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    Ref = models.IntegerField(blank=True,null=True)
    def __str__(self):
        return self.Nom_Client

class FactureMoto(models.Model):
    Num_Facture = models.IntegerField(null=True,default=0)
    def __int__(self):
        return self.Num_Facture

class BLMoto(models.Model):
    Num_BL = models.IntegerField(null=True,default=0)
    def __int__(self):
        return self.Num_Facture

moto/models.py
from django.db import models

# Create your models here.
class Moto(models.Model):
    ID_Moto = models.IntegerField(blank=True,null=True,unique=True)
    date_entree = models.DateField(auto_now=False,blank=True,null=True)
    nom_moto = models.CharField(max_length=500)
    num_moteur = models.CharField(max_length=500,unique=True)
    FRN = models.CharField(max_length=500,blank=True)
    PA = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    PV = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    date_vente = models.DateField(auto_now=False,null=True)
    nom_client_1 = models.CharField(max_length=50, blank=True)
    CIN_Num_Client_1 = models.CharField(max_length=50, blank=True)
    PJ_CIN_Client_1_recto = models.FileField(blank=True,null=True,upload_to='images')
    PJ_CIN_Client_1_verso = models.FileField(blank=True,null=True,upload_to='images')
    tel_client_1 = models.CharField(max_length=50, blank=True)
    adresse_client_1 = models.CharField(max_length=50, blank=True)
    num_BL = models.IntegerField(null=True,unique=True)
    num_sur_facture = models.IntegerField(null=True,unique=True)
    PJ_Facture = models.FileField(blank=True, null=True, upload_to='images')
    nom_client_2 = models.CharField(max_length=50, blank=True)
    tel_client_2 = models.CharField(max_length=50, blank=True)
    adresse_client_2 = models.CharField(max_length=50, blank=True)
    CIN_Num_Client_2 = models.CharField(max_length=50, blank=True)
    PJ_CIN_Client_2_recto = models.FileField(blank=True,null=True,upload_to='images')
    PJ_CIN_Client_2_verso = models.FileField(blank=True,null=True,upload_to='images')
    montant_reparation = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    motif_reparation = models.CharField(max_length=500,blank=True)
    commercial = models.CharField(max_length=500,blank=True)
    volume_moteur = models.CharField(max_length=500,blank=True)
    PU_HT = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    TVA = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    PT = models.DecimalField(null=True,blank=True,decimal_places=2,max_digits=20)
    montant_lettre = models.CharField(max_length=500,blank=True)
    Ref = models.IntegerField(blank=True, null=True)
    archive = models.BooleanField(default=False)

    def __str__(self):
        return self.nom_moto

facture/forms.py
from django import forms
from django.forms import ModelForm
from operation.models import Operation
from django.core.exceptions import ValidationError
from decimal import Decimal, DecimalException
from django.utils import formats
from django.utils.encoding import force_text
from moto.models import Moto
from .models import FactureMoto

class Thousands(forms.DecimalField):
    def to_python(self, value):
        if value in self.empty_values:
            return None
        if self.localize:
            value = formats.sanitize_separators(value)
        value = force_text(value).strip().replace(' ', '')

        try:
            value = Decimal(value)
        except DecimalException:
            raise ValidationError(
                self.error_messages['invalid'], code='invalid')
        return value

class factureForm(ModelForm):
    Facture_Date_Facture = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':'form-control w3-margin-bottom','max': 'today'}),required=False)

    Facture_OT_Honoraire = Thousands(label='OT - Honoraire',max_digits=20, decimal_places=2, widget=forms.TextInput())

    Facture_Autres_Montant = Thousands(label='Autres montant',max_digits=20, decimal_places=2, widget=forms.TextInput())

    Facture_BAD_Montant = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Overstay_Montant = Thousands(label='Overstay',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Surestaries_Montant = Thousands(label='Surestaries',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Debarquement = Thousands(label='Debarquement',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Magasinage_Montant = Thousands(label='Magasinage',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Droit_Compromis = Thousands(label='Droit compromis',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Amende_Montant = Thousands(label='Amende',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_OV_Montant = Thousands(label='OV',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_OV_Docker = Thousands(label='Docker',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Montant_Fret = Thousands(label='Fret',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_Immobilisation = Thousands(label='Immobilisation',max_digits=20,decimal_places=2, widget=forms.TextInput())

    Facture_SousTotal = Thousands(max_digits=20,decimal_places=2, widget=forms.TextInput())

    TotalFacture = Thousands(max_digits=20,decimal_places=2, widget=forms.TextInput())
    Tax = Thousands(max_digits=20,decimal_places=2, widget=forms.TextInput())


    def __init__(self, *args, **kwargs):
        super(factureForm, self).__init__(*args, **kwargs)

        for name in self.fields.keys():
            if name != 'Facture_Date_Facture':
                self.fields[name].widget.attrs.update({'class': 'form-control'})
                self.fields[name].required = False

    class Meta:
        model = Operation
        fields = [
            'Facture_OT_Honoraire','Facture_Autres_Montant','Facture_BAD_Montant','Facture_Overstay_Montant','Facture_Surestaries_Montant','Facture_Debarquement','Facture_Magasinage_Montant','Facture_Droit_Compromis','Facture_Amende_Montant','Facture_OV_Montant','Facture_OV_Docker','Facture_Montant_Fret','Facture_Immobilisation','Facture_Num_Facture','Facture_Nom_Client','Facture_Adresse_Client','Facture_Contact_Client','Facture_email_client','Facture_Date_Facture','Facture_SousTotal','Tax','TotalFacture'
        ]


class factureMotoForm(ModelForm):
    """docstring for factureMoto."""
    PU_HT = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    TVA = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    PV = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    date_vente = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':'form-control w3-margin-bottom','max': 'today'}),required=False)
    num_sur_facture = forms.CharField(label="Num facture",widget=forms.TextInput())
    def __init__(self, *args, **kwargs):
        super(factureMotoForm, self).__init__(*args, **kwargs)

        for name in self.fields.keys():
            if name != 'Facture_Date_Facture':
                self.fields[name].widget.attrs.update({'class': 'form-control'})
                self.fields[name].required = False

    class Meta:
        model = Moto
        fields = [
        'nom_client_2','CIN_Num_Client_2','adresse_client_2','tel_client_2','volume_moteur','PU_HT','TVA','PT','montant_lettre','PV','date_vente','Ref','num_sur_facture'
        ]

class BLMotoForm(ModelForm):
    """docstring for factureMoto."""
    PU_HT = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    TVA = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    PV = Thousands(label='BAD',max_digits=20,decimal_places=2, widget=forms.TextInput())
    date_vente = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':'form-control w3-margin-bottom','max': 'today'}),required=False)
    num_BL= forms.CharField(label="Num BL",widget=forms.TextInput())

    def __init__(self, *args, **kwargs):
        super(BLMotoForm, self).__init__(*args, **kwargs)

        for name in self.fields.keys():
            if name != 'Facture_Date_Facture':
                self.fields[name].widget.attrs.update({'class': 'form-control'})
                self.fields[name].required = False

    class Meta:
        model = Moto
        fields = [
        'nom_client_1','CIN_Num_Client_1','adresse_client_1','tel_client_1','volume_moteur','PU_HT','TVA','PT','montant_lettre','PV','date_vente','Ref','num_BL'
        ]

facture/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib import messages

from operation.models import Operation
from .forms import factureForm, factureMotoForm, BLMotoForm
from operation.receptionForm import ReceptionForm
from moto.models import Moto
from facture.models import FactureMoto, BLMoto


# Create your views here.

def editFacture(request, id=None, pk=None):
    operation = get_object_or_404(Operation, pk=id)
    if request.method == 'POST':
        form = factureForm(request.POST, instance=operation)
        if form.is_valid():
            form.save()
            messages.success(request, "success")
        else:
            messages.error(request, "error")
    else:
        form = factureForm(instance=operation)
        recform = ReceptionForm(instance=operation)
        messages.success(request, "success")
    context = {
        'form': form,
        'id': operation.id,
        'pk': id
    }
    return render(request, 'facture/edit.html', context)


def previewFacture(request, id=None):
    Facture = get_object_or_404(Operation, pk=id)
    return render(request, 'facture/preview.html',
                  {'Facture': Facture, 'id': Facture.id, 'client': Facture.Facture_Nom_Client})


def initFacture(request):
    if request.is_ajax and request.method == 'GET':
        id = request.GET.get("id", None)
        print("id = ", id)
        curOp = Operation.objects.get(pk=id)
        Facture_OT_Honoraire = curOp.OT_Honoraire
        print("Facture_OT_Honoraire = ", Facture_OT_Honoraire)
        Facture_Autres_Montant = curOp.Autres_Montant
        Facture_BAD_Montant = curOp.BAD_Montant
        Facture_Overstay_Montant = curOp.Overstay_Montant
        Facture_Surestaries_Montant = curOp.Surestaries_Montant
        Facture_Debarquement = curOp.Montant_MICTSL
        Facture_Magasinage_Montant = curOp.Magasinage_Montant
        Facture_Droit_Compromis = curOp.Droit_Compromis
        Facture_Amende_Montant = curOp.Amende_Montant
        Facture_OV_Montant = curOp.OV_Montant
        Facture_OV_Docker = curOp.OV_Docker
        Facture_Montant_Fret = curOp.Montant_Fret
        Facture_Immobilisation = curOp.Immobilisation
        Facture_Nom_Client = curOp.Client

        return JsonResponse(
            {'Facture_OT_Honoraire': Facture_OT_Honoraire, 'Facture_Autres_Montant': Facture_Autres_Montant,
             'Facture_BAD_Montant': Facture_BAD_Montant, 'Facture_Overstay_Montant': Facture_Overstay_Montant,
             'Facture_Surestaries_Montant': Facture_Surestaries_Montant, 'Facture_Debarquement': Facture_Debarquement,
             'Facture_Magasinage_Montant': Facture_Magasinage_Montant,
             'Facture_Droit_Compromis': Facture_Droit_Compromis, 'Facture_Amende_Montant': Facture_Amende_Montant,
             'Facture_OV_Montant': Facture_OV_Montant, 'Facture_OV_Docker': Facture_OV_Docker,
             'Facture_Montant_Fret': Facture_Montant_Fret, 'Facture_Immobilisation': Facture_Immobilisation,
             'Facture_Nom_Client': Facture_Nom_Client}, status=200)


def editFactureMoto(request, id=None):
    moto = get_object_or_404(Moto, pk=id)
    pageTitle = "Moto n°" + str(id)

    if request.method == 'POST':
        form = factureMotoForm(request.POST, instance=moto)
        if form.is_valid():
            form.save()
            messages.success(request, "success")
        else:
            messages.error(request, 'error')
    else:
        form = factureMotoForm(instance=moto)
    context = {'form': form,
               'moto': moto,
               'pageTitle': pageTitle,
               'pk': id
               }
    return render(request, 'facture/editFacture/editFactureMoto.html', context)


def editBLMoto(request, id=None):
    moto = get_object_or_404(Moto, pk=id)
    numBLlast = BLMoto.objects.last()
    pageTitle = "Moto n°" + str(id)
    if request.method == 'POST':
        form = BLMotoForm(request.POST, instance=moto)
        if form.is_valid():
            form.save()
            messages.success(request, 'success')
        else:
            messages.error(request, 'error')
    else:
        form = BLMotoForm(instance=moto)
    context = {'form': form,
               'moto': moto,
               'pageTitle': pageTitle,
               'pk': id
               }
    return render(request, 'facture/editBL/editBLMoto.html', context)


def previewFactureMoto(request, id=None):
    Facture = get_object_or_404(Moto, pk=id)
    pageTitle = "Moto n°" + str(Facture.ID_Moto)
    return render(request, 'facture/previewFacture/previewFactureMoto.html',
                  {'Facture': Facture, 'pageTitle': pageTitle})


def previewBLMoto(request, id=None):
    Facture = get_object_or_404(Moto, pk=id)
    pageTitle = "Moto n°" + str(Facture.ID_Moto)
    return render(request, 'facture/previewBL/previewBLMoto.html', {'Facture': Facture, 'pageTitle': pageTitle})

facture/templates/facture/previewBL/btnRedirPrev.html
<div class="">
  <a href="{% url 'index' %}" class="btn btn-secondary"><i class="fas fa-chevron-left fa-fw"></i>Retour</a>
  <button class="btn btn-success" onclick="ExportPdf()"><i class="fa fa-file-pdf fa-fw"></i> Export PDF</button>
</div>

facture/templates/facture/previewBL/previewBLMoto.html
{% extends "base/main.html" %}
{% load static %}
{% block content %}
{% include "facture/previewBL/previewBLMotoWredir.html" %}
{% endblock content %}
{% block js %}
<script type="text/javascript">
  $(document).ready(function(){
    $('#pageTitle').addClass('fas fa-motorcycle fa-fw w3-margin-right');
    $('#motoMenu').addClass("active");
  })
</script>
<script src="{% static 'facture/js/jszip.min.js' %}" charset="utf-8"></script>
<script src="{% static 'facture/js/kendo.all.min.js' %}" charset="utf-8"></script>
<script src="{% static 'facture/js/script.js' %}" charset="utf-8"></script>

{% endblock js %}

facture/templates/facture/previewBL/previewBLMotoTemplate.html
{% load l10n %}
{% load static %}
<link rel="stylesheet" href="{% static 'facture/css/kendo.common-material.min.css' %}">
<link rel="stylesheet" href="{% static 'facture/css/kendo.material.min.css' %}">
<link rel="stylesheet" href="{% static 'facture/css/customp.css' %}">
<h2 class="text-center" id='ptitle'>Prévisualisation du BL</h2>
<hr>
{% localize on %}
<style media="screen">
  #facture {
    color: black !important
  }

  table {
    color: black !important
  }
</style>
<br>
<div class="row justify-content-center" id="facture">
  <div class="col-md-8 col-lg-8 pre-scrollable" style="max-height:55vh">
    <div class="invoice overflow-auto" id="myCanvas">
      <div>
        <header>
          <div class="row">
            <div class="col">
              <img src="{% static 'base/assets/LogoTIA.jpeg' %}" data-holder-rendered="true" style="height:170px" />
            </div>
            <div class="col company-details">
              <h2 class="name">
                TIA MOTO SARLU
              </h2>
              <div>Ny Tsara Indrindra hAtrany</div>
              <div>Siège social: Lot IVX 72B Bis Ankazomanga</div>
              <div>Vente de scooter occasion et accessoires</div>
              <div>Tél: 0330393155</div>
              <div>NIF: 2004105069</div>
              <div>Stat: 46101112020010758</div>
              <div>RCS: 2020 B 00714</div>
            </div>
          </div>
          <div class="text-center">
            <h1>BON DE LIVRAISON</h1>
          </div>
        </header>
        <main>
          <div class="row contacts">
            <div class="col invoice-to" style="width:70%">
              <div class="text-gray-light">LIVRÉ À:</div>
              <h4 class="to">{{Facture.nom_client_1}}</h4>
              <div class="address">CIN - {{Facture.CIN_Num_Client_1}}</div>
              <div class="email">{{Facture.adresse_client_1}}</div>
              <div class="contacts">
                {{Facture.tel_client_1}}
              </div>
            </div>
            <div class="col invoice-details">
              <h4>N°<span id="factnum">{{Facture.num_BL}}</span></h4>
              <div class="date">Date: <span>{{Facture.date_vente}}</span></div>
            </div>
          </div>

          <div class="table-responsive">
            <table class="table" cellspacing="0" cellpadding="0" id='templcontent'
              style="border-right:medium solid black;">
              <thead>
                <tr>
                  <th class="text-center" style="width:10%"><b>Ref</b></th>
                  <th class="text-left" style="width:30%"><b>DESIGNATION</b></th>
                  <th class="text-center"><b>PU HT</b></th>
                  <th class="text-center"><b>TVA</b></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="w3-large text-center">{{Facture.Ref}}</td>
                  <td class="text-left">
                    <p>
                      {{Facture.nom_moto}}
                    </p>
                    <p>Moteur n°</p>
                    <p><b>{{Facture.num_moteur}}</b></p>
                    <p>{{Facture.volume_moteur}}</p>
                  </td>
                  <td class="qty text-right" id="id_PU_HT">{{Facture.PU_HT}} Ar</td>
                  <td class="total text-right" id="id_TVA">{{Facture.TVA}} Ar</td>
                </tr>
              </tbody>
              <tfoot style="border:none!important">
                <tr>
                  <td colspan="2"></td>
                  <td colspan="1" style="border:1px solid black" id="id_PV">PRIX TOTAL TTC</td>
                  <td class="text-right" style="border:1px solid black">{{Facture.PV}} Ar</td>
                </tr>
              </tfoot>
            </table>
          </div>
      </div>
      <table class="table table-bordered" style="
                border-width:1px!important;
                border-color:#000!important;
                border-bottom-width:1px!important;
                border-right-width:1px!important;">
        <tr>
          <td>
            {{Facture.montant_lettre}}

          </td>
        </tr>
      </table>
      <br>
      <div class="table-responsive">
        <table class="table table-borderless">
          <tr class="text-center" style="border:none!important">
            <td>Vendeur</td>
            <td>Client</td>
          </tr>
        </table>
      </div>
      <div class="w3-padding-48">
      </div>
      </main>
      <footer>
        Les marchandises vendues ne sont ni reprises ni échangées.
      </footer>
    </div>
  </div>
</div>
{% endlocalize %}
<hr class="mb-3">
<div class="row justify-content-center">
  {% block btnRedir %}{% endblock btnRedir %}
</div>

facture/templates/facture/previewBL/previewBLMotoWredir.html
{% extends "facture/previewBL/previewBLMotoTemplate.html" %}
{% load static %}
{% block btnRedir %}
{% include "facture/previewBL/btnRedirPrev.html" %}
{% endblock btnRedir %}